# Generated by Django 4.2.4 on 2024-07-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='note2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(blank=True, max_length=50)),
                ('year_of_study2', models.CharField(max_length=15)),
                ('note2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='note3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name3', models.CharField(blank=True, max_length=50)),
                ('year_of_study3', models.CharField(max_length=15)),
                ('note3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='note4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name4', models.CharField(blank=True, max_length=50)),
                ('year_of_study4', models.CharField(max_length=15)),
                ('note4', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='notes',
            new_name='note1',
        ),
    ]
