# Generated by Django 4.2.4 on 2024-07-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_notes', '0002_note2_note3_note4_rename_notes_note1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note1',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='note1',
            old_name='note',
            new_name='notes1',
        ),
        migrations.RenameField(
            model_name='note1',
            old_name='year_of_study',
            new_name='year_of_study1',
        ),
        migrations.RenameField(
            model_name='note2',
            old_name='note2',
            new_name='notes2',
        ),
        migrations.RenameField(
            model_name='note3',
            old_name='note3',
            new_name='notes3',
        ),
        migrations.RenameField(
            model_name='note4',
            old_name='note4',
            new_name='notes4',
        ),
    ]
