# Generated by Django 4.2.4 on 2024-07-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_notes', '0004_notif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='conversation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notif',
            name='name_of_teacher',
            field=models.CharField(blank=True, default='notification', max_length=100),
        ),
    ]
