# Generated by Django 4.2.4 on 2024-07-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_notes', '0005_alter_notif_conversation_alter_notif_name_of_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='name_of_teacher',
            field=models.CharField(default='notification', max_length=100),
        ),
    ]
