# Generated by Django 4.2.4 on 2024-07-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_child', models.CharField(blank=True, max_length=30, null=True)),
                ('parent_child_name', models.CharField(blank=True, max_length=50, null=True)),
                ('typ', models.CharField(max_length=10)),
                ('gmail', models.TextField()),
            ],
        ),
    ]
