# Generated by Django 4.2.4 on 2024-07-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_signin_phone_alter_signin_gmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_child_chat', models.CharField(blank=True, max_length=50)),
                ('chats_words', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='signin',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
