# Generated by Django 4.2.4 on 2024-07-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_chat_model_alter_signin_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='name_child',
        ),
        migrations.AddField(
            model_name='signin',
            name='child_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='signin',
            name='parent_child_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
