# Generated by Django 4.2.4 on 2024-07-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_signin_name_child_signin_child_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='child_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='signin',
            name='parent_child_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
