# Generated by Django 4.2.4 on 2024-07-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_signin_child_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chat_model',
        ),
    ]
