# Generated by Django 4.2.4 on 2024-07-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_delete_chat_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
