# Generated by Django 4.2.4 on 2024-07-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_parent_chat', models.CharField(blank=True, max_length=50)),
                ('chats_words', models.TextField()),
            ],
        ),
    ]
