# Generated by Django 4.2.4 on 2024-07-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabic_parent', '0002_alter_chat_model_chats_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_model',
            name='name_of_children',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
