# Generated by Django 4.2.4 on 2024-07-13 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arabic_parent', '0003_chat_model_name_of_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_model',
            old_name='name_of_children',
            new_name='name_of_child',
        ),
    ]
